"""Backward-compatibility shim — implementation moved to ai_assistant.registries.action_handlers."""
from ai_assistant.registries.action_handlers import (  # noqa: F401
    NO_LINKED_DOCUMENT_MESSAGE,
    text,
    parse_payload,
    priority,
    related_document,
    valid_related_document,
    recommendation_title,
    recommendation_description,
    validate_permission,
    validate_user,
    response,
    create_task,
    follow_up,
    assign_user,
    draft_email,
    open_document,
    calendar_event,
    notify_user,
    add_comment,
    reminder,
    activity_timeline,
    HANDLERS,
    time_call,
)
